title: NEURO_QUAL
description: NEURO_QUAL is an open-access qualitative resource for neurosurgeons and neurosurgery, developed by members of the NIHR GHRG ABSI at the University of Cambridge.
theme: just-the-docs

url: https://brangsmith.github.io/nq

aux_links:
  Template Repository: https://github.com/brangsmith/nq
