title: NEURO_QUAL
description: NEURO_QUAL is an open-access qualitative resource for neurosurgeons and neurosurgery, developed by members of the NIHR GHRG ABSI at the University of Cambridge.
theme: just-the-docs

url: https://brangsmith.github.io/nq

aux_links:
  NIHR GHRG ABSI: absi.world
  Podcasts: https://open.spotify.com/show/7MYupa3n8lF3HWNZNqjYSn?si=wRaEuIdRQrGefqON13iifQ&dl_branch=1&nd=1&dlsi=ecad593a875e4358
  Contact: mailto:bgs30@cam.ac.uk?subject=NEUROQUAL
